---
all:
  vars:
    ansible_user: root
    ensure_keys_for: [root]

    ensure_hostname: true
    ensure_hosts: true

    unattend_disable: true
    update_pkg_cache: true
    features:
      evpn: false

    one_version: '7.0'
    one_pass: '<<TBA>>'
    db_backend: SQLite
    vn:
      pubridge:
        managed: true
        template:
          VN_MAD: bridge
          PHYDEV: <<TBA>>
          BRIDGE: br0
          AR:
            TYPE: IP4
            IP: <<TBA>>
            SIZE: <<TBA>>
          DNS: <<TBA>>
          NETWORK_MASK: <<TBA>>
          GATEWAY: <<TBA>>
      vxlan:
        managed: true
        template:
          VN_MAD: vxlan
          PHYDEV: <<TBA>>
          BRIDGE: br1
          VLAN_ID: <<TBA>>
          GUEST_MTU: 1450
          AR:
            TYPE: IP4
            IP: <<TBA>>
            SIZE: <<TBA>>
          NETWORK_ADDRESS: <<TBA>>
          NETWORK_MASK: <<TBA>>

frontend:
  hosts:
    fe: { ansible_host: <<TBA>> }

node:
  hosts:
    host01: { ansible_host: <<TBA>> }
    host02: { ansible_host: <<TBA>> }